# Generated by Django 5.0.1 on 2024-01-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='inventory',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='featured',
        ),
    ]
